/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oso_app;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.table.TableColumn;
/**
 *
 * @author DELL
 */
public class form_pesanan extends javax.swing.JFrame {
koneksi kon=new koneksi();
private Object [][] datasementara=null;
private String[]labelsementara={"Id Produk","Jumlah"};
    /**
     * Creates new form form_pesanan
     */
    public form_pesanan() {
        initComponents();
        tid_produk.setEnabled(false);
setTanggal();
kon.setKoneksi();
nonaktif();
    }
    
    public String KodeProduk;
public String getKodeProduk() {
return KodeProduk;
}
void setTanggal(){
java.util.Date skrg = new java.util.Date();
java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd");
ttanggal.setText(kal.format(skrg));
}

public String getnoPS()
{
String urutan=null;
try{
kon.rs=kon.st.executeQuery("select right(id_pesanan,3)+1 from pesanan as Nomor order by id_pesanan desc");
if(kon.rs.next())
{
urutan=kon.rs.getString(1);
while(urutan.length()<3)
urutan="0"+urutan;
urutan="PS-"+urutan;
}else
{
urutan="PS-"+"001";
}
}catch(Exception e){
JOptionPane.showMessageDialog(null,"No PS Error : "+e);
}
return urutan;
}

private void BacaTabelSementara(){
try{
String sql="Select *From sementara order by id_produk";
kon.rs=kon.st.executeQuery(sql);
ResultSetMetaData m=kon.rs.getMetaData();
int kolom=m.getColumnCount();
int baris=0;
while(kon.rs.next()){
baris=kon.rs.getRow();
}
datasementara=new Object[baris][kolom];
int x=0;
kon.rs.beforeFirst();
while(kon.rs.next()){
datasementara[x][0]=kon.rs.getString("id_produk");
datasementara[x][1]=kon.rs.getString("qty");
x++;
}
tbl_pesanan.setModel(new DefaultTableModel(datasementara,labelsementara));
}
catch(SQLException e){
JOptionPane.showMessageDialog(null, e);
}
}

private void SimpanSementara(){
try{
String sql="insert into sementara values('"+tid_produk.getText()+"','"+tjumlah.getText()+"')";
kon.st.executeUpdate(sql);
BacaTabelSementara();
}
catch(SQLException e){
JOptionPane.showMessageDialog(null,e);
}
}

private void HapusSementara(){
int row=tbl_pesanan.getSelectedRow();
try{
String sql="Delete from sementara where id_produk='"+(String)tbl_pesanan.getValueAt(row,0)+"'";
kon.st.executeUpdate(sql);
BacaTabelSementara();
}
catch(SQLException e){
JOptionPane.showMessageDialog(null, e);
}
}
private void hapusSementara2(){
try{
String sql="Delete from sementara ";
kon.st.executeUpdate(sql);
BacaTabelSementara();
}
catch(SQLException e){
JOptionPane.showMessageDialog(null, e);
}
}
void simpanPesanan(){
try{
String sql = "insert into pesanan values ('"+tid_pesan.getText() +"','"+ttanggal.getText()+"')";
kon.st.executeUpdate(sql);
String detail = "insert item_pesanan select '" +tid_pesan.getText() +"',id_produk,qty from sementara ";

kon.st.executeUpdate(detail);
JOptionPane.showMessageDialog(this,"Berhasil disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
}catch(SQLException e){
System.out.println("koneksi gagal"+ e.toString());
}
}
private void BersihField(){
tid_produk.setText("");
tjumlah.setText("");
}
private void aktif(){
tid_produk.setEnabled(true);
tjumlah.setEnabled(true);
}
private void nonaktif(){
ttanggal.setEnabled(false);
tid_pesan.setEnabled(false);
tid_produk.setEnabled(false);
tjumlah.setEnabled(false);
bsimpan.setEnabled(false);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ttanggal = new javax.swing.JTextField();
        tid_pesan = new javax.swing.JTextField();
        tid_produk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tjumlah = new javax.swing.JTextField();
        browse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pesanan = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        bkurang = new javax.swing.JButton();
        btambah = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        btutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tanggal Pesanan");

        jLabel2.setText("Id Pesanan");

        jLabel3.setText("Id Produk");

        tid_pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tid_pesanActionPerformed(evt);
            }
        });

        jLabel4.setText("Jumlah");

        tjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjumlahActionPerformed(evt);
            }
        });

        browse.setText("...");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });

        tbl_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_pesanan);

        jLabel5.setText("ENTER");

        bkurang.setText("-");
        bkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkurangActionPerformed(evt);
            }
        });

        btambah.setText("Tambah");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bbatal.setText("Batal");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        btutup.setText("Tutup");
        btutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ttanggal)
                            .addComponent(tid_pesan, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tid_produk)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(browse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bkurang))
                    .addComponent(btutup, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tid_pesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tid_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bkurang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btambah)
                    .addComponent(bsimpan)
                    .addComponent(bbatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btutup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tid_pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tid_pesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tid_pesanActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
boolean closable = true;
dataproduk dataProduk = new dataproduk(null, closable);
dataProduk.pesanan = this;
dataProduk.setVisible(true);
dataProduk.setResizable(true);
tid_produk.setText(KodeProduk);        // TODO add your handling code here:
    }//GEN-LAST:event_browseActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
aktif();
bbatal.setEnabled(true);
bsimpan.setEnabled(true);
btambah.setEnabled(false);
tid_produk.setEnabled(false);
tid_pesan.setText(getnoPS());
tid_pesan.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btambahActionPerformed

    private void tjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjumlahActionPerformed
try{
String sql="select *from sementara where id_produk='" +tid_produk.getText()+ "'";
kon.rs=kon.st.executeQuery(sql);
if(kon.rs.next())
{
JOptionPane.showMessageDialog(this,"Kode Sudah Dipilih...","Informasi", JOptionPane.INFORMATION_MESSAGE);
browse.requestFocus();
tid_produk.setText("");
}
else
{
SimpanSementara();
if (JOptionPane.showConfirmDialog(this, "Mau Tambah Barang?", "konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
tid_produk.requestFocus();
tid_produk.setText("");
tjumlah.setText("");
} else {
BersihField();
bsimpan.requestFocus();
return;
}
}
}
catch(SQLException e){
JOptionPane.showMessageDialog(null, e);
}        // TODO add your handling code here:
    }//GEN-LAST:event_tjumlahActionPerformed

    private void bkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkurangActionPerformed
HapusSementara();        // TODO add your handling code here:
    }//GEN-LAST:event_bkurangActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
hapusSementara2();
bsimpan.setEnabled(false);
btambah.setEnabled(true);
tid_pesan.setText("");
BersihField();
nonaktif();        // TODO add your handling code here:
    }//GEN-LAST:event_bbatalActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
simpanPesanan();
hapusSementara2();
bsimpan.setEnabled(false);
btambah.setEnabled(true);
BersihField();
tid_pesan.setText("");
nonaktif();        // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanActionPerformed

    private void btutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btutupActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bkurang;
    private javax.swing.JButton browse;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btambah;
    private javax.swing.JButton btutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_pesanan;
    private javax.swing.JTextField tid_pesan;
    private javax.swing.JTextField tid_produk;
    private javax.swing.JTextField tjumlah;
    private javax.swing.JTextField ttanggal;
    // End of variables declaration//GEN-END:variables
}
