/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oso_app;

/**
 *
 * @author DELL
 */
public class menuutama extends javax.swing.JFrame {

    /**
     * Creates new form menuutama
     */
    public menuutama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnlogout = new javax.swing.JMenuItem();
        mnkeluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnproduk = new javax.swing.JMenuItem();
        mnpegawai = new javax.swing.JMenuItem();
        mnsupplier = new javax.swing.JMenuItem();
        mnkategori = new javax.swing.JMenuItem();
        nmpesanan = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        mnlogout.setText("Logout");
        mnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnlogout);

        mnkeluar.setText("Keluar");
        mnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnkeluarActionPerformed(evt);
            }
        });
        jMenu1.add(mnkeluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master");

        mnproduk.setText("Produk");
        mnproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnprodukActionPerformed(evt);
            }
        });
        jMenu2.add(mnproduk);

        mnpegawai.setText("Pegawai");
        mnpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnpegawaiActionPerformed(evt);
            }
        });
        jMenu2.add(mnpegawai);

        mnsupplier.setText("Supplier");
        mnsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnsupplierActionPerformed(evt);
            }
        });
        jMenu2.add(mnsupplier);

        mnkategori.setText("Kategori");
        mnkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnkategoriActionPerformed(evt);
            }
        });
        jMenu2.add(mnkategori);

        jMenuBar1.add(jMenu2);

        nmpesanan.setText("Pesanan");
        nmpesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmpesananMouseClicked(evt);
            }
        });
        nmpesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmpesananActionPerformed(evt);
            }
        });
        jMenuBar1.add(nmpesanan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnpegawaiActionPerformed
form_pegawai pegawai = new form_pegawai();
pegawai.setLocationRelativeTo(null);
pegawai.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_mnpegawaiActionPerformed

    private void mnkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnkategoriActionPerformed
form_kategori kategori = new form_kategori();
kategori.setLocationRelativeTo(null);
kategori.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_mnkategoriActionPerformed

    private void mnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnlogoutActionPerformed
this.dispose();
form_login Login = new form_login();
Login.setLocationRelativeTo(null);
Login.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_mnlogoutActionPerformed

    private void mnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnkeluarActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_mnkeluarActionPerformed

    private void mnprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnprodukActionPerformed
form_produk produk = new form_produk();
produk.setLocationRelativeTo(null);
produk.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_mnprodukActionPerformed

    private void mnsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnsupplierActionPerformed
form_supplier supplier = new form_supplier();
supplier.setLocationRelativeTo(null);
supplier.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_mnsupplierActionPerformed

    private void nmpesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmpesananActionPerformed
form_pesanan pesanan = new form_pesanan();
pesanan.setLocationRelativeTo(null);
pesanan.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_nmpesananActionPerformed

    private void nmpesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmpesananMouseClicked
form_pesanan pesanan = new form_pesanan();
pesanan.setLocationRelativeTo(null);
pesanan.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_nmpesananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem mnkategori;
    private javax.swing.JMenuItem mnkeluar;
    private javax.swing.JMenuItem mnlogout;
    private javax.swing.JMenuItem mnpegawai;
    private javax.swing.JMenuItem mnproduk;
    private javax.swing.JMenuItem mnsupplier;
    private javax.swing.JMenu nmpesanan;
    // End of variables declaration//GEN-END:variables
}
